# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/pycosat, last modified Thu Jun  2 15:02:48 2016
# ------------------------------------------------

package:
    name: pycosat
    version: 0.6.1
source:
    git_rev: 0.6.1
    git_url: https://github.com/ContinuumIO/pycosat.git
build:
    number: '1'
requirements:
    build:
        - python
    run:
        - python
test:
    files:
        - qg3-08.cnf
        - uf20-098.cnf
    imports:
        - pycosat
about:
    description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
        This

        package provides efficient Python bindings to picosat on the C level, i.e.

        when importing pycosat, the picosat solver becomes part of the Python

        process itself.

        '
    dev_url: https://github.com/ContinuumIO/pycosat
    home: https://github.com/ContinuumIO/pycosat
    license: MIT
    license_file: LICENSE
    summary: Python bindings to the picosat SAT solver
