package:
  name: enum34
  version: 1.1.6

source:
  fn: enum34-1.1.6.tar.gz
  url: https://pypi.python.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz
  md5: 5f13a0841a61f7fc295c514490d120d0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ordereddict        [py26]

test:
  imports:
    - enum

about:
  home: https://pypi.python.org/pypi/enum34
  license: BSD
  summary: Robust enumerated type support in Python
  description: |
    This module defines two enumeration classes that can be used to define
    unique sets of names and values. It also defines one decorator.
  doc_url: https://pypi.python.org/pypi/enum34
  dev_url: https://github.com/certik/enum34
