package:
  name: pip
  version: 8.1.2

source:
  fn: pip-8.1.2.tar.gz
  url: https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz
  md5: 87083c0b9867963b29f7aba3613e8f4a
  patches:
    - cio_conf.patch

build:
  number: 0
  entry_points:
    - pip = pip:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - wheel

test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip

about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip
